[package]
name = "junoswap-staking"
authors = ["Volume Fi"]
version = { workspace = true }
edition = { workspace = true }
description = "Contract aimed just for migration - take JunoSwap staked LP and migrate to PALOMA DEX"
license = { workspace = true }
repository = { workspace = true }
homepage = "https://www.palomachain.com"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
cw2 = { workspace = true }
cw20 = { workspace = true }
cw-utils = { workspace = true }
thiserror = { workspace = true }

palomadex = { workspace = true }
palomadex-factory = { workspace = true }
palomadex-stake = { workspace = true }
# this is old version of cw20 used by wasmswap
wasmswap_cw20 = { package = "cw20", version = "0.10.0" }
# this is the staking contract we are migrating from (use the state variables there)
stake-cw20 = { git="https://github.com/DA0-DA0/dao-contracts", tag="v0.3.0" }
# this is the pool contract we will withdraw from
wasmswap = { git="https://github.com/Wasmswap/wasmswap-contracts", tag="v1.1.2-beta" }

[dev-dependencies]
anyhow = { workspace = true }
cw-multi-test = { workspace = true }
serde = { workspace = true }
wasmswap_cw20-base = { package = "cw20-base", version = "0.10.0" }
wasmswap_cw-utils = { package = "cw-utils", version = "0.11" }
palomadex-factory = { workspace = true }
palomadex-pair = { workspace = true }
cw20-base = { workspace = true }
